# fly.toml app configuration file generated for ronum-young-thunder-7893 on 2023-11-16T22:09:56+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ronum"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8501
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
