name: GitHub Actions
on: [ push ]
concurrency: ci

env:
  APP_NAME: "ronum"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Build
        run: |
          docker build -t "$APP_NAME" .

      - name: Test
        run: |
          docker run "$APP_NAME" python -m flake8
          docker run "$APP_NAME" python -m unittest --verbose

  deploy:
    name: Deploy app
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
