[server]
port = 8501
enableStaticServing = true
fileWatcherType = "none" # "auto"
enableCORS = false
enableXsrfProtection = true

[client]
showErrorDetails = false
toolbarMode = "minimal"

[browser]
gatherUsageStats = false
